services:
  - type: web
    name: task-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
